### ISSUE TITLE
社区详情-未标记精华的帖子不应该在“精华帖子”标签页展示

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/citydream#102]
1.
![tim 20180604110110](https://user-images.githubusercontent.com/31264647/40896374-212f15fc-67e7-11e8-9f72-7accacbad672.png)
# 
**2.未标记精华的帖子也在“精华帖子”标签页展示。**

**Comment by keith-hou** [comment]
这个没有问题
