### ISSUE TITLE
会员俱乐部--精选商品显示规则不正确

### ISSUE THREAD

**Issue by WangDong-123** [hzcsTeam/citydream#121]
当前问题：精选商品显示的后台管理员最近添加的前三个商品
期望结果：精选商品应该显示后台管理员主动推荐的商品
<img width="289" alt="image" src="https://user-images.githubusercontent.com/31264647/41339111-9fe7b2e6-6f26-11e8-8f8a-9d2cb1571829.png">

**Comment by keith-hou** [comment]
已修改
